### PR TITLE
#163230428 Build REST GET Endpoint for Upcoming Meetups

### PR DESCRIPTION
**Pull request by matthenge**
#### What does this PR do?
Create a GET Endpoint for fetching upcoming Meetups.
#### Description of Task to be completed?
-create GET upcoming meetups model
-create GET upcoming meetups view
-Run tests
#### How should this be manually tested?
-Clone the repository to your local machine [here](https://github.com/matthenge/Questioner-API.git)
-Cd into the directory
-Install requirements
-Test using Postman
#### What are the relevant pivotal tracker stories?
#163230428
https://www.pivotaltracker.com/story/show/163230428
#### Screenshot
screenshot from 2019-01-15 20-45-55

### CODE REVIEW

**Comment by Ogollah** [comment]
This is a good job.

**Comment by tirgei** [comment]
Looks good

**Comment by khwilo** [comment]
I suggest you add your PT story as a link like this `[PT_STORY](PT_STROY_LINK)`

**Comment by billthebuilder** [comment]
Awesome job on this

**Pull request merged**
